server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  # springBoot2.6.x后必须开启此项否则swagger启动报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    #数据库索引
    database: 4
    host: 192.168.36.128
    port: 6379
    #连接超时时间
    timeout: 5000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 配置七牛云权限密钥与上传的空间
qi-niu-oss:
  accessKey: kCQHwzjmeg6evh1NoX1PzuqMLD1Ekr3pk8CdCZt7
  secretKey: 3UrTuJqNMU5kXj2bFjnNoTkaXnJMd1PV6EMJKfwq
  bucket: lui-blog